.github/workflows/PythonFormatter.yml, .gitignore, README.md, requirements.txt, tools/constants.py, tools/update_students_list.py
Added in tool directory a script to allow admin to update the students list using a command.
Added a CI that checks for formatting before merging.
=> Inital setup for tools

requirements.txt, tools/constants.py, tools/update_students_list.py
Added a way to get the dot env file everywhere.
Fix missing lib
=> Fix dotenv path and requirements

tools/constants.py, tools/update_students_list.py
I resolved the issue where B-IIG was missing from the list of allowed programs.
Closing #9
=> Resolved B-IIG issue

bot/domain/student/student.py, requirements.txt
Added a student model with a JSON mixing.
Related to #5
=> Add student model

bot/cog/registration/register_member.py, tools/constants.py
A message welcoming people in the server has been created. I would like to know if it seems okay or if it needs something else added
=> Issue welcome message

bot/infra/cache/cache_item.py, bot/infra/cache/cache_repository.py, bot/infra/student/cached_student_repository.py, main.py
I've added a cache for the student repo.
I've made the cache extensible if we have other repos.
=> Add cache repository

bot/application/student/exceptions/missing_program_code_exception.py, bot/application/student/exceptions/student_already_exist.py, bot/application/student/student_service.py, bot/application/student/validators/program_code_validator.py, bot/cog/constants.py, bot/cog/exceptions/missing_arguments_exception.py, bot/cog/registration/add_student_request_factory.py, bot/cog/registration/register_member.py, bot/cog/request/add_student_request.py, bot/cog/request/register_student_request.py, bot/config/application_context.py, bot/config/development_context.py, bot/config/production_context.py, bot/domain/student/student_factory.py, bot/domain/student/student_repository.py, bot/domain/utility.py, bot/infra/student/cached_student_repository.py, bot/infra/student/mongodb_student_repository.py
Add command to register a student manually
=> Add student manually

bot/cog/decorators/role_check.py, bot/cog/registration/register_member.py, bot/domain/constants.py
Added a decorator that allow certains roles to execute a command.
Close #36
=> Add restriction to command by role

bot/application/student/validators/program_code_validator.py, bot/cog/registration/register_member.py, bot/domain/constants.py, bot/domain/student/student_factory.py
Added membre honorifique role.
Close #37
=> Add membre honorifique

bot/application/discord/discord_service.py
Decided to not apply a nickname for the server owner.
Closing #31
=> fix owner role when applying nickname

bot/application/discord/discord_service.py, bot/application/discord/events/student_registered/student_registered_observable.py, bot/application/discord/events/student_registered/student_registered_observer.py, bot/application/student/student_service.py, bot/cog/constants.py, bot/cog/registration/factory/unregister_student_request_factory.py, bot/cog/registration/register_member.py, bot/cog/request/unregister_student_request.py, bot/domain/student/attributs/discord_user_id.py, bot/domain/student/student_repository.py, bot/infra/student/cached_student_repository.py, bot/infra/student/mongodb_student_repository.py
Added a command to unregister a user
Closing #46
=> Unregister user

bot/cog/association/association.py, bot/cog/association/embed/aeglo_embed.py, bot/cog/association/embed/asetin_embed.py
Added description embed for each association.
Closing #53
=> Add association embed

bot/application/student/student_service.py, bot/domain/student/student_repository.py, bot/infra/student/cached_student_repository.py, bot/infra/student/mongodb_student_repository.py
Check if a person tries to register multiple accounts.
Closing #49
=> Add double verification when registered

bot/cog/constants.py, bot/cog/registration/register_member.py
=> Add missing translation

.dockerignore, README.md, dockerfile, requirements.txt
=> Updated to 3.10

.github/workflows/PythonFormatter.yml, README.md, bot/resource/cog/registration/register_member.py, dev-requirements.txt, main.py, requirements.txt
=> Add log to joined member

tools/configuration_common.py, tools/migrate_discord_students.py
Fix migration. People with long name can now be migrated.
Also, membre honorifique are skipped.
=> Fix migration tool

bot/application/task/kick_unregistered_user_task.py, bot/config/context/application_context.py, bot/config/context/development_context.py, bot/config/context/production_context.py, bot/domain/task/task.py, bot/domain/task/task_scheduler.py, requirements.txt
=> Add task scheduler

bot/application/discord/discord_service.py, bot/application/discord/event/member_removed/member_removed_observable.py, bot/application/discord/event/member_removed/member_removed_observer.py, bot/application/discord/event/student_registered/student_registered_observable.py, bot/application/discord/event/student_registered/student_registered_observer.py, bot/application/student/student_service.py, bot/config/service_locator.py, bot/domain/student/student_repository.py, bot/infra/student/cached_student_repository.py, bot/infra/student/mongodb_student_repository.py, bot/resource/cog/registration/register_member.py, tools/migrate_discord_students.py
=> Add event on member removed

README.md, bot/application/discord/event/member_removed/member_removed_observer.py, tools/migrate_discord_students.py, tools/update_students_list.py
=> Fix readme to interact with tools

bot/application/task/kick_unregistered_user_task.py, bot/application/task/sentence_of_the_day_task.py, bot/config/context/development_context.py, bot/config/context/production_context.py, requirements.txt
=> Add sentence of the day

bot/application/task/sentence_of_the_day_task.py
=> Fix remove print

README.md, tools/__main__.py
=> Rework readme

.dockerignore, .github/workflows/build-deploy-docker-image.yml, .github/workflows/docker-build.yml, README.md, bot/config/context/application_context.py, bot/config/context/development_context.py, bot/config/context/docker_context.py, bot/config/context/dotenv_configuration.py, docker-compose.yml, dockerfile, main.py
=> Modify load env configuration

docker-compose.yml
=> Fix grammar error on docker-compose.yml

README.md, bot/config/logger/logger.py, docker/docker-compose.yml
=> Persist log with docker

bot/application/discord/discord_service.py, bot/application/student/student_service.py, bot/infra/student/mongodb_student_repository.py
Added more logs to have more traceability.
=> Add more logs

bot/application/student/student_service.py
=> Fix AddStudent already exist

bot/infra/student/cached_student_repository.py, bot/infra/student/exception/cannot_add_student_exception.py, bot/infra/student/exception/cannot_unregister_student_exception.py, bot/infra/student/exception/cannot_update_student_exception.py, bot/infra/student/exception/mongo_fail_operation_exception.py, bot/infra/student/exception/student_not_found_exception.py, bot/infra/student/mongodb_student_repository.py
=> Correct log string

bot/resource/cog/registration/factory/add_student_request_factory.py, bot/resource/cog/registration/factory/request_factory.py, bot/resource/cog/registration/register_member.py
=> Fix composed name for add_student command

.github/workflows/build-push-docker-image.yml, README.md
Found a suitable name for the workflow
=> Rename workflow for a suitable name

bot/infra/cache/cache_repository.py, bot/infra/cache/exception/cache_find_operation_not_found_exception.py, bot/infra/cache/exception/cache_item_not_found_exception.py, bot/infra/student/cached_student_repository.py
=> Add find operation in cache

bot/application/task/sentence_of_the_day_task.py, bot/domain/student/attribut/ni.py, bot/domain/student/student.py, bot/resource/decorator/prohibit_self_message.py, bot/resource/decorator/role_check.py
Found some dirty code to refactor.
=> Refactor decorators & attributs

bot/application/student/exceptions/invalid_name_format_exception.py, bot/application/student/student_service.py, bot/application/student/validators/name_validator.py
Closing #119 
Considering
```py
if not self.__name_validator.validate(add_student_request.firstname):
raise InvalidNameFormatException(add_student_request.firstname)
if not self.__name_validator.validate(add_student_request.lastname):
raise InvalidNameFormatException(add_student_request.lastname)
if not self.__ni_validator.validate(add_student_request.ni):
raise InvalidNIFormatException(add_student_request.ni)
if not self.__program_code_validator.validate(add_student_request.program_code):
raise MissingProgramCodeException(add_student_request.program_code)
```
Maybe it is time to use pydantic ?
=> Add name validator

bot/application/student/student_service.py, bot/config/environment/context/application_context.py, bot/infra/cache/cache_repository.py, bot/resource/constants.py
Closing #122 
Added a check before entering into the infra to register.
Exception mapper was missing.
=> Fix registration bug by casting the correct message

bot/resource/cog/association/embed/aeglo_embed.py, bot/resource/cog/association/embed/asetin_embed.py
=> Modify ASETIN and AEGLO information

bot/application/task/kick_unregistered_user_task.py, bot/resource/cog/association/embed/asetin_embed.py, tools/__main__.py, tools/configuration_common.py, tools/migrate_discord_students.py, tools/renew_students_list.py, tools/update_students_list.py
=> Add renew command

bot/application/discord/discord_service.py, bot/application/discord/event/member_removed/member_removed_observable.py, bot/application/discord/event/member_removed/member_removed_observer.py, bot/application/discord/event/student_registered/student_registered_observable.py, bot/application/discord/event/student_registered/student_registered_observer.py, bot/application/student/student_service.py, bot/resource/cog/registration/register_member.py
Closing #132 
I've put await everywhere to eliminate tasks complexity.
=> Remove multitasking

bot/resource/cog/error_handler/error_handler.py
=> Fix unknow command & private message response

bot/application/discord/discord_service.py
=> Remove nickname when unregister

bot/config/environment/context/application_context.py, bot/resource/cog/registration/register_member.py, bot/resource/constants.py, bot/resource/decorator/user_in_server.py, bot/resource/exception/user_not_in_server_exception.py
=> Block registration if not in server

docker/.dockerignore, docker/dockerfile
=> Add log directory into docker

bot/application/student/exceptions/invalid_discord_id_format_exception.py, bot/application/student/student_service.py, bot/application/student/validators/discord_id_validator.py, bot/domain/utility.py, bot/resource/cog/registration/factory/force_register_student_request_factory.py, bot/resource/cog/registration/register_member.py, bot/resource/cog/registration/request/force_register_student_request.py, bot/resource/constants.py
=> Add force register command

bot/application/student/student_service.py, bot/infra/student/cached_student_repository.py, bot/resource/cog/registration/factory/force_unregister_student_request_factory.py, bot/resource/cog/registration/register_member.py, bot/resource/cog/registration/request/force_unregister_student_request.py, bot/resource/cog/registration/request/unregister_student_request.py, bot/resource/constants.py
=> Self unregister and admin force_unregister

bot/resource/cog/registration/register_member.py, docker/script/updater.sh
=> fix self register

tools/renew_students_list.py
Added a way to reset member nickname.
Fix when file is missing.
=> Reset student name & check file existance

bot/application/student/validators/name_validator.py, tools/renew_students_list.py
=> Update with accents chars

bot/application/discord/discord_service.py
Closing #137 
Sends a message to the user if it's name is too long.
=> Send message name too long

docker/script/updater.sh
=> Check for new update on updater.sh

bot/application/discord/discord_service.py, tools/__main__.py, tools/give_integration_role.py, tools/renew_students_list.py
=> Add give_integration_role

bot/application/discord/discord_service.py
=> Add try & except for nickname changed

tools/give_integration_role.py
Now, you can pass an evelya or a google xlsx.
=> Support both Google Form & Evelya for integration tool command

bot/application/task/kick_unregistered_user_task.py
=> From 1 week to 2 weeks for kick member

bot/domain/constants.py
=> Fix admin role name

bot/application/task/kick_unregistered_user_task.py, docker/script/updater.sh
If the person does not a have a nickname it display NONE. Impossible to know who is that person!
=> Add more explicit log when kicking
